import os, discord
from discord.ext import commands
 
token = input("Enter Token")
client = commands.Bot(command_prefix=commands.when_mentioned_or("$"))
os.system('cls')
os.system(f'press bot')
os.system(f'mode 120,40')




@client.event
async def on_ready():
  print(f""" \u001b[31m

------------------------------
""")



@client.event
async def on_message(message):
    channel = message.channel
    if message.content.endswith('?'):

        await message.channel.send ('ILL SLIT UR THROAT')
        await message.channel.send ('LOSER FUCK')
        await message.channel.send ('UR BLACK LOOOOL')
        await message.channel.send ('MA SON')
        await message.channel.send ('COME LINK WITH ME FAG')
        await message.channel.send ('I')
        await message.channel.send ('OWN')
        await message.channel.send ('U')
        await message.channel.send ('SONNY')
        await message.channel.send ('BOY')
        await message.channel.send ('DO SUM')
        await message.channel.send ('ILL 200 PUMP UR GRANDMA')
        await message.channel.send ('WEAK FUCK')
        await message.channel.send ('U SUCK')
        await message.channel.send ('I OWN U')
        await message.channel.send ('LOOOOOOOOOOOOOOOOL')
        await message.channel.send ('WEAK FUCK')
        await message.channel.send ('NIGGA THOUGHT HE WAS COOL')
        await message.channel.send ('GET BETTER FAG')
        await message.channel.send ('ILL RUN')
        await message.channel.send ('U')
        await message.channel.send ('OFF')
        await message.channel.send ('CORD')
        await message.channel.send ('LOOL')
        await message.channel.send ('LOOOOOOOL')
        await message.channel.send ('ILL LYNCH UR MONKEY FAMILY')
        await message.channel.send ('AND RIP OUT UR SPINE AND USE IT AS A ROPE')
        await message.channel.send ('DUMBFUCK')
        await message.channel.send ('TIRED OF YO SLOW ASS')
        await message.channel.send ('LOOOOOOOOOOOOOOL')
        await message.channel.send ('OOOOOOOOOLOLO')
        await message.channel.send ('OLOLOLOLOLOL')
        await message.channel.send ('SHITTY ASS NERD')
        await message.channel.send (':nerd:')
        await message.channel.send ('WEAK')
        await message.channel.send ('BITCH')
        await message.channel.send ('LOLO')
        await message.channel.send ('LOOL')
        await message.channel.send ('OLOL')
        await message.channel.send ('LOLO')
        await message.channel.send ('good loser')
        await message.channel.send ('ill drown ur mother in her own blood')
        await message.channel.send ('lame ass faggot')
        await message.channel.send ('u nasty homosexual fuck')
        await message.channel.send ('i feel bad for u faggot')
        await message.channel.send ('bald ass faggot')
        await message.channel.send ('i own this nigga')
        await message.channel.send ('stinky fuck')
        await message.channel.send ('??')
        await message.channel.send ('????')
        await message.channel.send ('this nigga is horrible')
        await message.channel.send ('big ass loser bro.')
        await message.channel.send ('just commit already')
        await message.channel.send ('LOL')
        await message.channel.send ('shitty ass troll')
        await message.channel.send ('ur weak as fuck nigga')
        await message.channel.send ('bitch ass boy')
        await message.channel.send ('come die')
        await message.channel.send ('loser fuck')
        await message.channel.send ('ur ass nigga')
        await message.channel.send ('u cant last with ur father')
        await message.channel.send ('ur hands getting tired or sum?')
        await message.channel.send ('weak ass homosexual fuck')
        await message.channel.send ('ma son')
        await message.channel.send ('ur weak')
        await message.channel.send ('LOOOL')
        await message.channel.send ('OL')
        await message.channel.send ('L')
        await message.channel.send ('OLO')
        await message.channel.send ('LO')
        await message.channel.send ('O')
        await message.channel.send ('LOLOLO')
        await message.channel.send ('L')
        await message.channel.send ('YOU WEAK BITCH KEEP UP WITH ME')
        await message.channel.send ('KEEP CHATTING SON')
        await message.channel.send ('NO BREAKS FOR YOU')
        await message.channel.send ('WHY YOU SLOWING DOWN KEEP IT GOING')
        await message.channel.send ('WEAK FUCKING BITCH')
        await message.channel.send ('FUCKING RETARD DOESNT KNOW WHAT TO SAY')
        await message.channel.send ('YOU SUCK PUSSY')
        await message.channel.send ('LMFAOOO I OWN U')
        await message.channel.send ('WEAK ASS BITCH FOCUS UP SON')
        await message.channel.send ('MA SON')
        await message.channel.send ('LMFAOAOAOAO')
        await message.channel.send ('WEAK ASS FUCKING TROLL CANT PRESS ME')
        await message.channel.send ('FOCUS LOLL UR ASS')
        await message.channel.send ('DUMBASS WEAK TROLL')
        await message.channel.send ('GET FASTER')
        await message.channel.send ('DUMB BITCH YOU FEAR ME')
        await message.channel.send ('FUCKING TROLL')
        await message.channel.send ('SHUT')
        await message.channel.send ('THE')
        await message.channel.send ('FUCK')
        await message.channel.send ('UP')
        await message.channel.send ('AND')
        await message.channel.send ('COME')
        await message.channel.send ('LINK WITH ME')
        await message.channel.send ('FUCKING')
        await message.channel.send ('PUSSY')
        await message.channel.send ('UR')
        await message.channel.send ('BLACK')
        await message.channel.send ('LMFAOOOOO)



client.run(token, bot=False)
